#!/bin/bash
echo "\nAdd which file(s)?: "
read -r ADDWHAT
git add $ADDWHAT
echo "\nCommit comment? :"
read -r COMMENT
git commit -m $COMMENT
echo "\nWhich branch to push from?: "
read -r FROMBRANCH
echo "\nAnd where to pugh to?: "
read -r TOBRANCH
git push $TOBRANCH $FROMBRANCH
