#!/bin/bash
read -p "Which file(s) would you like to include/add?: " ADDWHAT
git add $ADDWHAT
read -p "Please add a comment for this commit: " COMMENT
git commit -m "$(echo $COMMENT)"
read -p "Which branch to push from?: " FROMBRANCH
read -p "And where to push to?: " TOBRANCH
git push $TOBRANCH $FROMBRANCH
